import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "第60回 蛟龍祭 場内サイト",
  description: "Generated by Koryo Fes Executive Committee",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
